# Generated by Django 5.0.6 on 2024-06-25 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='idRegion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.IntegerField(db_column='idTipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('desc', models.CharField(db_column='Descripcion', max_length=5000)),
                ('precio', models.IntegerField(db_column='Precio')),
                ('tipo', models.ForeignKey(db_column='Tipo', on_delete=django.db.models.deletion.CASCADE, to='PetStore.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254, primary_key=True, serialize=False, unique=True)),
                ('pass1', models.CharField(db_column='pass', max_length=128)),
                ('direccion', models.CharField(db_column='direccion', max_length=255)),
                ('codZip', models.CharField(db_column='codZip', max_length=20)),
                ('region', models.ForeignKey(db_column='idRegion', on_delete=django.db.models.deletion.CASCADE, to='PetStore.region')),
            ],
        ),
    ]
