# Generated by Django 5.0.6 on 2024-06-27 19:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='idRegion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipoAnimal',
            fields=[
                ('id_tipo', models.IntegerField(db_column='Tipo_Animal', primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.IntegerField(db_column='idTipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.IntegerField(db_column='idAnimal', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('desc', models.CharField(db_column='Descripcion', max_length=5000)),
                ('raza', models.CharField(db_column='Raza', max_length=50)),
                ('tipo', models.ForeignKey(db_column='Tipo', on_delete=django.db.models.deletion.CASCADE, to='PetStore.tipoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('desc', models.CharField(db_column='Descripcion', max_length=5000)),
                ('precio', models.IntegerField(db_column='Precio')),
                ('tipo', models.ForeignKey(db_column='Tipo', on_delete=django.db.models.deletion.CASCADE, to='PetStore.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('cod_zip', models.CharField(blank=True, db_column='codZip', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, db_column='idRegion', null=True, on_delete=django.db.models.deletion.CASCADE, to='PetStore.region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
