# Generated by Django 5.0.6 on 2024-06-25 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoAnimal',
            fields=[
                ('id_tipo', models.IntegerField(db_column='Tipo_Animal', primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.IntegerField(db_column='id_animal', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('desc', models.CharField(db_column='Descripcion', max_length=5000)),
                ('Raza', models.CharField(db_column='Raza', max_length=20)),
                ('tipo', models.ForeignKey(db_column='Tipo', on_delete=django.db.models.deletion.CASCADE, to='PetStore.tipoanimal')),
            ],
        ),
    ]
